language: node_js
node_js:
- 0.1
before_script:
- npm install -g grunt-cli
- npm install -g bower
- npm install --no-bin-links
- bower install
env:
  global:
  - secure: CNL+xtInMvMUR4YAX/IhpugChOlfbi5Ms8yTXVflGM1TvwSZe/eY0awGhxdH/dpjZMcTHcCjD6lG5utagJ84nSyXcQYkFxsbcWxmSolN6ik8oHAVBAkYLS3RlHyc3iQELJDMIxR7Kicl+7dv6vb71nbRkIIjAyB9advdQBUzdvk=
  - secure: hBtJ8saCD/alLbVAVdWa8fWo2JpGBp+fD7ZDY9MSC25lPhRvBT9vgZt/d3vy8vdroaZjvNBuJLqTXTpbgv9YsZ+MNj6+ExdzhSpMi64FRndNgf3I5Ru8Tsc7eHIT/pb2jaVm7rPWMMTBRj8Q5o8MCbwJukSzjvgMnBnsSOr93fo=
